#!/usr/bin/env python3
"""Full project-analysis smoke for the Gateway Agent Planner.

This is a protocol-level downstream simulation rather than a model-quality
benchmark.  It proves the outer planner can drive a chat-only upstream through
the intended project analysis workflow:

  update_plan -> Skill -> code graph structure -> core flow search
  -> symbol snippet/trace -> key file read -> final synthesis

The upstream fake never emits tools.  Tool use blocks are generated by the
Gateway planner and "executed" here as a downstream client would do.
"""
from __future__ import annotations

import json
import os
import pathlib
import tempfile
import threading
import sys
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import src.toolcall_gateway as gateway
from src.gateway_tool_runtime import run_tool_orchestration


PROJECT_NAME = "Users-sanbo-Desktop-ai_tool_functioncall"
QNAME = "Users-sanbo-Desktop-ai_tool_functioncall.src.gateway_tool_runtime.run_tool_orchestration"


class FakeClient:
    def __init__(self, responses: list[dict[str, Any]]) -> None:
        self.responses = list(responses)
        self.requests: list[tuple[str, dict[str, Any]]] = []
        self.lock = threading.Lock()

    def forward(self, path: str, body: dict[str, Any]) -> dict[str, Any]:
        with self.lock:
            self.requests.append((path, body))
            if not self.responses:
                raise AssertionError("no fake upstream response left")
            return self.responses.pop(0)


def _chat_response(text: str) -> dict[str, Any]:
    return {
        "id": "chatcmpl_project_analysis_fake",
        "object": "chat.completion",
        "model": "weak-chat-only",
        "choices": [{"index": 0, "message": {"role": "assistant", "content": text}, "finish_reason": "stop"}],
        "usage": {"prompt_tokens": 1, "completion_tokens": 1},
    }


def _tool_schemas() -> list[dict[str, Any]]:
    return [
        {
            "name": "update_plan",
            "input_schema": {
                "type": "object",
                "properties": {"plan": {"type": "array"}, "explanation": {"type": "string"}},
                "required": ["plan"],
                "additionalProperties": False,
            },
        },
        {
            "name": "Skill",
            "input_schema": {
                "type": "object",
                "properties": {"skill": {"type": "string"}, "args": {"type": "string"}},
                "required": ["skill"],
                "additionalProperties": False,
            },
        },
        {
            "name": "mcp__codebase_memory_mcp__search_graph",
            "input_schema": {
                "type": "object",
                "properties": {"project": {"type": "string"}, "query": {"type": "string"}},
                "required": ["project", "query"],
                "additionalProperties": False,
            },
        },
        {
            "name": "mcp__codebase_memory_mcp__get_code_snippet",
            "input_schema": {
                "type": "object",
                "properties": {
                    "project": {"type": "string"},
                    "qualified_name": {"type": "string"},
                    "include_neighbors": {"type": "boolean"},
                },
                "required": ["project", "qualified_name"],
                "additionalProperties": False,
            },
        },
        {
            "name": "mcp__codebase_memory_mcp__trace_path",
            "input_schema": {
                "type": "object",
                "properties": {
                    "project": {"type": "string"},
                    "function_name": {"type": "string"},
                    "direction": {"type": "string"},
                    "mode": {"type": "string"},
                    "depth": {"type": "integer"},
                },
                "required": ["project", "function_name"],
                "additionalProperties": False,
            },
        },
        {
            "name": "Read",
            "input_schema": {
                "type": "object",
                "properties": {"file_path": {"type": "string"}},
                "required": ["file_path"],
                "additionalProperties": False,
            },
        },
    ]


def _tool_result(block: dict[str, Any]) -> dict[str, Any]:
    name = str(block.get("name") or "")
    call_id = str(block.get("id") or "")
    args = dict(block.get("input") or {})
    if name == "update_plan":
        content = json.dumps({"ok": True, "accepted": True}, ensure_ascii=False)
    elif name == "Skill":
        content = "Successfully loaded skill: codebase-onboarding"
    elif name.endswith("search_graph"):
        query = str(args.get("query") or "")
        if "core request flow" in query:
            content = json.dumps(
                {
                    "results": [
                        {
                            "qualified_name": QNAME,
                            "name": "run_tool_orchestration",
                            "file_path": "src/gateway_tool_runtime.py",
                        }
                    ],
                    "notes": "Core flow routes through run_tool_orchestration; see README.md for usage.",
                },
                ensure_ascii=False,
            )
        else:
            content = json.dumps(
                {
                    "architecture": "Gateway handler -> gateway_tool_runtime -> gateway_agent_planner",
                    "files": ["README.md", "src/gateway_tool_runtime.py", "src/gateway_agent_planner.py"],
                },
                ensure_ascii=False,
            )
    elif name.endswith("get_code_snippet"):
        content = (
            f'{{"qualified_name":"{QNAME}",'
            '"source":"def run_tool_orchestration(path, body, client=None):\\n'
            '    # delegates planning to gateway_agent_planner\\n'
            '    return _run_tool_orchestration_scoped(path, body, client)",'
            '"file_path":"src/gateway_tool_runtime.py","related":["README.md"]}'
        )
    elif name.endswith("trace_path"):
        content = json.dumps(
            {
                "function_name": args.get("function_name"),
                "calls": ["_direct_downstream_tool_request_response", "prepare_upstream_body"],
                "callers": ["gateway_http_handler"],
                "files": ["README.md", "src/gateway_tool_runtime.py"],
            },
            ensure_ascii=False,
        )
    elif name == "Read":
        content = "# README\n\nGateway usage and architecture. PROJECT-ANALYSIS-READ-OK\n"
    else:
        raise AssertionError(f"unexpected tool in project-analysis smoke: {name} {args}")
    return {"type": "tool_result", "tool_use_id": call_id, "content": content, "is_error": False}


def run_smoke() -> dict[str, Any]:
    old_config = gateway.CONFIG_PATH
    old_cwd = os.getcwd()
    old_ws = os.environ.get("GATEWAY_WORKSPACE_ROOT")
    old_project = os.environ.get("GATEWAY_CODEBASE_MEMORY_PROJECT")
    with tempfile.TemporaryDirectory(prefix="agent-planner-project-smoke-") as td:
        root = pathlib.Path(td)
        (root / "README.md").write_text("# SmokeProject\n", encoding="utf-8")
        (root / "src").mkdir()
        (root / "src" / "gateway_tool_runtime.py").write_text("def run_tool_orchestration(): pass\n", encoding="utf-8")
        gateway.CONFIG_PATH = root / "gateway.config.json"
        cfg = gateway._default_config()
        cfg["gateway"]["workspace_root"] = str(root)
        cfg["gateway"]["tool_mode"] = "orchestrate"
        cfg["upstream"]["tools_enabled"] = "adapter"
        cfg["upstream"]["protocol"] = "openai_chat"
        cfg["upstream"]["capabilities"]["supports_tools"] = False
        cfg["upstream"]["capabilities"]["supports_function_calls"] = False
        gateway.save_config(cfg)
        os.chdir(root)
        os.environ["GATEWAY_WORKSPACE_ROOT"] = str(root)
        os.environ["GATEWAY_CODEBASE_MEMORY_PROJECT"] = PROJECT_NAME

        final_text = "项目分析完成：PROJECT-ANALYSIS-FINAL-OK"
        client = FakeClient([_chat_response(final_text)])
        messages: list[dict[str, Any]] = [
            {"role": "system", "content": "Available skills:\n- codebase-onboarding"},
            {"role": "user", "content": "分析这套项目，给出架构、核心请求流程和风险"},
        ]
        steps: list[str] = []
        final_response: dict[str, Any] | None = None

        for _ in range(12):
            body = {"model": "weak-chat-only", "messages": messages, "tools": _tool_schemas(), "max_tokens": 4096}
            response = run_tool_orchestration("/v1/messages", body, client)
            if response.get("stop_reason") != "tool_use":
                final_response = response
                break
            tool_uses = [b for b in response.get("content") or [] if isinstance(b, dict) and b.get("type") == "tool_use"]
            if not tool_uses:
                raise AssertionError(f"tool_use stop without tool_use blocks: {response}")
            messages.append({"role": "assistant", "content": tool_uses})
            results = []
            for block in tool_uses:
                steps.append(str(block.get("name")))
                results.append(_tool_result(block))
            messages.append({"role": "user", "content": results})
        else:
            raise AssertionError("project-analysis planner loop did not terminate")

        if final_response is None:
            raise AssertionError("no final response")
        final_payload = json.dumps(final_response, ensure_ascii=False)
        expected_order = [
            "update_plan",
            "Skill",
            "mcp__codebase_memory_mcp__search_graph",
            "mcp__codebase_memory_mcp__search_graph",
        ]
        if steps[:4] != expected_order:
            raise AssertionError(f"unexpected initial project-analysis steps: {steps!r}")
        if "mcp__codebase_memory_mcp__get_code_snippet" not in steps:
            raise AssertionError(f"missing get_code_snippet step: {steps!r}")
        if "mcp__codebase_memory_mcp__trace_path" not in steps:
            raise AssertionError(f"missing trace_path step: {steps!r}")
        if "Read" not in steps:
            raise AssertionError(f"missing key Read step: {steps!r}")
        if final_text not in final_payload:
            raise AssertionError(f"final synthesis missing marker: {final_payload[:1000]}")
        if len(client.requests) != 1:
            raise AssertionError(f"expected exactly one final upstream synthesis call, got {len(client.requests)}")
        synthesis_prompt = json.dumps(client.requests[0][1], ensure_ascii=False)
        required_evidence = ["Gateway Agent Planner evidence", QNAME, "PROJECT-ANALYSIS-READ-OK"]
        missing = [marker for marker in required_evidence if marker not in synthesis_prompt]
        if missing:
            raise AssertionError(f"final synthesis prompt missing evidence {missing}: {synthesis_prompt[:1500]}")
        return {
            "ok": True,
            "workspace": str(root),
            "steps": steps,
            "upstream_calls": len(client.requests),
            "final_text": final_text,
        }
    # unreachable while tempdir context owns workspace


def main() -> int:
    old_config = gateway.CONFIG_PATH
    old_cwd = os.getcwd()
    old_ws = os.environ.get("GATEWAY_WORKSPACE_ROOT")
    old_project = os.environ.get("GATEWAY_CODEBASE_MEMORY_PROJECT")
    try:
        result = run_smoke()
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0
    finally:
        gateway.CONFIG_PATH = old_config
        os.chdir(old_cwd)
        if old_ws is None:
            os.environ.pop("GATEWAY_WORKSPACE_ROOT", None)
        else:
            os.environ["GATEWAY_WORKSPACE_ROOT"] = old_ws
        if old_project is None:
            os.environ.pop("GATEWAY_CODEBASE_MEMORY_PROJECT", None)
        else:
            os.environ["GATEWAY_CODEBASE_MEMORY_PROJECT"] = old_project


if __name__ == "__main__":
    raise SystemExit(main())
